language: elixir

elixir:
  - 1.3
  - 1.4

otp_release:
  - 18.3
  - 19.3
  - 20.0

env:
  - EXHAL_POISON_VERSION="~> 2.2"
  - EXHAL_POISON_VERSION="~> 3.1"

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
